---
title: Listen Up
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  team:
    title: Team
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    image: 
    description: 
- scope:
    path: ''
    type: services
  values:
    permalink: "/services/:title/"
    layout: service
- scope:
    path: ''
    type: clients
  values:
    image: 
    is-featured: 
    is-front: 
    website: 
    facebook: 
    twitter: 
    instagram: 
    spotify: 
    soundcloud: 
    youtube: 
    apple: 
    layout: client
- scope:
    path: ''
    type: team
  values:
    image: 
    job-title: 
    is-featured: 
    email: 
url: http://listen-up.biz
description: Listen Up provides a bespoke 360 promotional service offering radio,
  club, online and print campaigns in the UK and worldwide.
permalink: pretty
exclude: 
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Listen Up Online Promotions Ltd
email: hello@listen-up.biz
google_site_verification: 
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: https://www.facebook.com/listenupbiz
  instagram: https://www.instagram.com/listenupbiz/
  twitter: https://twitter.com/ListenUpbiz
  linkedin: https://www.linkedin.com/company/listen-up-music-pr
